define([], function() {
  return {
    "PropertyPaneDescription": "Beschreibung",
    "BasicGroupName": "Gruppen Name",
    "DescriptionFieldLabel": "Beschreibungsfeld",
    "SortFieldLabel": "Sortieren",
    "OptionsFieldLabel": "max Items",
    "ColorFieldLabel": "Farben",
    "SortFileUnsorted": "unsortiert",
    "SortFileAsc": "aufsteigende Daten",
    "SortFileDesc": "absteigende Daten",
    "SortFileAscD": "aufsteigende Beschriftungen",
    "SortFileDescD": "absteigende Beschriftungen",
    "ColorFieldStandard": "Standard",
    "ColorFieldMono1": "Monochrome 1",
    "ColorFieldMono2": "Monochrome 2",
    "ColorFieldColor1": "Farbig 1",
    "ColorFieldColor2": "Farbig 2",
    "ModeFieldLabel": "Modus",
    "ModeFieldNormal": "Normal",
    "ModeFieldCount": "Zählen",
    "ModeFieldGroup": "Gruppieren und Zählen",
    "GeneralFieldLabel": "Generell",
    "DataGroupName": "Daten",
    "ModeFieldList": "Liste",
    "LabelFieldLabel": "Beschriftungsspalte",
    "DataFieldLabel": "Datenspalte",
    "PlaceholderDescription": "Bitte konfigurieren Sie das Web Part.",
    "PlaceholderButton": "Konfigurieren"
  }
});