define([], function() {
  return {
    "PropertyPaneDescription": "Description",
    "BasicGroupName": "Group Name",
    "DescriptionFieldLabel": "Description Field",
    "SortFieldLabel": "Sort",
    "OptionsFieldLabel": "max Items",
    "ColorFieldLabel": "Colors",
    "SortFileUnsorted": "unsorted",
    "SortFileAsc": "ascending data",
    "SortFileDesc": "descending data",
    "SortFileAscD": "ascending labels",
    "SortFileDescD": "descending labels",
    "ColorFieldStandard": "Standard",
    "ColorFieldMono1": "Monochrome 1",
    "ColorFieldMono2": "Monochrome 2",
    "ColorFieldColor1": "Colorful 1",
    "ColorFieldColor2": "Colorful 2",
    "ModeFieldLabel": "Mode",
    "ModeFieldNormal": "Normal",
    "ModeFieldCount": "Count",
    "ModeFieldGroup": "Group by Count",
    "GeneralFieldLabel": "General",
    "DataGroupName": "Data",
    "ModeFieldList": "List",
    "LabelFieldLabel": "Label Column",
    "DataFieldLabel": "Data Column",
    "PlaceholderDescription": "Please configure the Web Part.",
    "PlaceholderButton": "Configure"
  }
});